services:
    mysql:
        image: mysql:latest
        container_name: mysql-database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: bitcoin_and_sp500_price_prediction
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
